<a href="https://colab.research.google.com/github/Tech-savvyPavithra/Data_Science/blob/main/Numpy_Internship.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practice

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#Get Dimension
a.ndim

1

In [ ]:
#Get Type
a.dtype

dtype('int64')

In [ ]:
#Get Size
a.itemsize

4

In [ ]:
#Get total Size
a.nbytes

12

In [ ]:
#Get number of elements
a.size

3

In [ ]:
#Accessing,Changing specific element
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element
a[1,5]

13

In [ ]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy
a[0,1:-1:2]
a[1,5]
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [ ]:
#3D example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element
b[0,1,1]

4

In [ ]:
#Replace
b[:,1,:]=[[9,9,9],[8,8]]
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
#Replace
b[:,1,:]=[[9,9,9],[8,8,8]]
print(b)

ValueError: could not broadcast input array from shape (2,3) into shape (2,2)

In [ ]:
#Replace
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


Assignment Workouts

In [ ]:
# Create a numpy array from a list of numbers
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [ ]:
# Create a numpy array with values from 0 to 9
b = np.arange(10)
print(b)

# Create a numpy array with values from 10 to 20 with a step of 2
c = np.arange(10, 20, 2)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18]


In [ ]:
# Create a numpy array with shape (2, 3) and filled with ones
d = np.ones((2, 3))
print(d)

# Create a numpy array with shape (3, 2) and filled with zeros
e = np.zeros((3, 2))
print(e)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Create an array with 5 random integers from 0 to 10
l = np.random.randint(0, 10, 5)
print(l)

# Create an array with 4 random floats from a normal distribution
m = np.random.normal(size=4)
print(m)

# Create a 2x2 array with random values from a uniform distribution
n = np.random.uniform(size=(2, 2))
print(n)

[6 1 1 2 7]
[ 0.6973106  -0.39768761  0.09440997 -0.28947807]
[[0.66664558 0.52340814]
 [0.0747979  0.14349721]]


In [ ]:
# Creating a 2D array of random numbers between 0 and 1
a = np.random.rand(4, 5)
print(a)

# Calculating the mean, standard deviation, and sum of the array
mean = np.mean(a)
std = np.std(a)
sum = np.sum(a)
print("Mean:", mean)
print("Standard deviation:", std)
print("Sum:", sum)

[[0.41169216 0.40449023 0.14536152 0.2633402  0.18826901]
 [0.08913564 0.17495271 0.77715035 0.57593197 0.47658031]
 [0.09564365 0.48107531 0.06559748 0.23884449 0.487539  ]
 [0.26116145 0.18053939 0.40327196 0.86769616 0.75030521]]
Mean: 0.3669289100145262
Standard deviation: 0.2330815277866317
Sum: 7.338578200290525


In [ ]:
# Creating a 1D array of 12 elements
b = np.arange(12)
print(b)

# Reshaping the array to a 3x4 matrix
b = b.reshape(3, 4)
print(b)

# Transposing the matrix
b = b.T
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# Creating two 2D arrays of shape 2x3 and 3x2
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[7, 8], [9, 10], [11, 12]])
print(c)
print(d)

# Performing matrix multiplication on c and d
e = np.matmul(c, d)
print(e)

# Performing dot product on c and d
f = np.dot(c, d)
print(f)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [ ]:
# Create a 2D array of shape (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

# Get the size, shape, number of dimensions, and number of bytes of the array
size = np.size(a)
shape = np.shape(a)
ndim = np.ndim(a)
print("Size:", size)
print("Shape:", shape)
print("Number of dimensions:", ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Size: 12
Shape: (3, 4)
Number of dimensions: 2


In [ ]:
# Create a 2D array of shape (2, 3) and filled with zeros
b = np.zeros((2, 3))
print(b)

# Create a 2D array of shape (2, 3) and filled with ones
c = np.ones((2, 3))
print(c)

# Create a 2D array of shape (2, 3) and filled with uninitialized values
d = np.empty((2, 3))
print(d)

# Create a 2D identity matrix of shape (3, 3)
e = np.identity(3)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Create a 1D array with values from 0 to 9
f = np.arange(10)
print(f)

# Create a 1D array with 5 values evenly spaced between 0 and 1
g = np.linspace(0, 1, 5)
print(g)

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create a 1D array of 12 elements
h = np.arange(12)
print(h)

# Reshape the array to a 3x4 matrix
i = np.reshape(h, (3, 4))
print(i)

# Flatten the matrix to a 1D array
j = np.ravel(i)
print(j)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Create a 2D array of shape (2, 3)
k = np.array([[1, 2, 3], [4, 5, 6]])
print(k)

# Calculate the sum of the array
l = np.sum(k)
print(l)

# Calculate the sum of the array along the rows
m = np.sum(k, axis=0)
print(m)

# Calculate the sum of the array along the columns
n = np.sum(k, axis=1)
print(n)

# Calculate the maximum of the array
o = np.max(k)
print(o)

# Calculate the minimum of the array
p = np.min(k)
print(p)

# Calculate the square root of the array
q = np.sqrt(k)
print(q)

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
6
1
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
# Create a 2D array of shape (2, 3)
r = np.array([[1, 2, 3], [4, 5, 6]])
print(r)

# Transpose the array
s = np.transpose(r)
print(s)

# Transpose the array using the attribute .T
t = r.T
print(t)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Create two 2D arrays of shape (2, 3)
ab = np.array([[1, 2, 3], [4, 5, 6]])
ac = np.array([[7, 8, 9], [10, 11, 12]])
print(ab)
print(ac)

# Perform matrix addition on ab and ac
ad = ab + ac
print(ad)

# Perform matrix addition on ab and ac using np.add
ae = np.add(ab, ac)
print(ae)

# Perform matrix multiplication on ab and ac
af = ab * ac
print(af)

# Perform matrix multiplication on ab and ac using np.multiply
ag = np.multiply(ab, ac)
print(ag)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]
[[ 7 16 27]
 [40 55 72]]


In [ ]:
# Create two 2D arrays of shape (2, 3)
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
print(a)
print(b)

# Perform subtraction on a and b
c = a - b
print(c)

# Perform subtraction on a and b using np.subtract
d = np.subtract(a, b)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
# Create two 2D arrays of shape (2, 3)
e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([[7, 8, 9], [10, 11, 12]])
print(e)
print(f)

# Perform division on e and f
g = e / f
print(g)

# Perform division on e and f using np.divide
h = np.divide(e, f)
print(h)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
